### ISSUE TITLE
Color ramp text wraps when model panel requires scroll bar

### ISSUE THREAD

**Issue by tomwayson** [Esri/landscape-modeler-js#11]
![image](https://f.cloud.github.com/assets/662944/1863471/69044404-77e3-11e3-85d4-251063afa409.png)

**Comment by skocher42** [comment]
I noticed that the Transparency slider also wraps, but if you change "width:150px" to "width:110px" in WeightedOverlayModelDesigner.html, that no longer happens -- easy fix.
