### ISSUE TITLE
Add instructions on how to point to a different weighted overlay mosaic service

### ISSUE THREAD

**Issue by tomwayson** [Esri/landscape-modeler-js#24]
Need to address:
- service url
- app id
- raster function names
- dummyRasterId
- queryParameters

Should document w/ comments in config.js and then add instructions to README.

**Comment by mhogeweg** [comment]
that would be great. I've been working to connect the app to some ocean layers from GMED and would benefit from the configuration documentation. you can also add the need to have the additional attributes in the mosaic dataset and their specific meaning:
- InputRanges ( type: esriFieldTypeString , alias: InputRanges , length: 256 )
- OutputValues ( type: esriFieldTypeString , alias: OutputValues , length: 256 )
- NoDataRanges ( type: esriFieldTypeString , alias: NoDataRanges , length: 256 )
- RangeLabels ( type: esriFieldTypeString , alias: RangeLabels , length: 256 )
- NoDataRangeLabels ( type: esriFieldTypeString , alias: NoDataRangeLabels , length: 256 )
- Title ( type: esriFieldTypeString , alias: Title , length: 50 )
- Url ( type: esriFieldTypeString , alias: Url , length: 1024 )

**Comment by tomwayson** [comment]
The need for those fields is documented here:

http://resources.arcgis.com/en/help/landscape-modeler/prepare-data/

The new instructions in this repo should include a link to that document.

I also agree that the document could do a better job of explaining the specific meaning of those fields.
