### ISSUE TITLE
Run Model Checkered Result

### ISSUE THREAD

**Issue by irmcinto** [Esri/landscape-modeler-js#35]
When I run the landscape modeler with my own data, the final results come out to a checkered result. I am not sure why it is. I have up loaded a screen shot of what I am talking about, and the landscape modeler is hosted on 152.7.99.47/landscape-modeler-js/src. I would appreciate some insight.

Thanks in Advance!
![issue](https://cloud.githubusercontent.com/assets/17200662/14060333/b5329584-f337-11e5-99eb-2fc3cea95eab.JPG)

**Comment by paniello** [comment]
Hi irmcinto, it's hard to tell what's wrong without seeing your data, your mosaic, and knowing the versions of ArcGIS Desktop and Server you are using.  Can you provide the configuration info and give access to the data?  Thanks.

**Comment by irmcinto** [comment]
Hello  paniello,
Thanks for the response, but I was able to finally figure it out. I do apologize for not updating the page.
